lesson_1/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

lesson_1/geekshop/basketapp/urls.py
from django.urls import path


from .views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>/', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

lesson_1/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path ('', mainapp.main, name='main'),
    path ('contact/', mainapp.contact, name='contact'),
    path ('products/', include('mainapp.urls', namespace='products')),
    path ('molinezia/', mainapp.molinezia, name='molinezia'),
    path ('neon/', mainapp.neon, name='neon'),
    path ('pecilia/', mainapp.pecilia, name='pecilia'),
    path ('auth/', include('authapp.urls', namespace='auth')),
    path ('admin/', admin.site.urls),
    path ('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson_1/geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    # path('product/{{product.name}}/', product.name, name={{product.name}}),
]

lesson_1/geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    # short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

lesson_1/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product



def main(request):
    return render(request, 'mainapp/index.html')

def products(request, pk=None):
    products = Product.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()

    if pk is not None:
        if pk:
           category = get_object_or_404(ProductCategory, pk=pk)
           products = products.filter(category=category)

        context = {'products': products, 'categories': ProductCategory.objects.all(), 'basket': basket, }
        return render(request, 'mainapp/products.html', context)

    else:
        hot_product = Product.objects.filter(is_hot=True).first()

        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all(), 'basket': basket, }
        return render(request, 'mainapp/hot_product.html', context)


def contact(request):
    return render(request, 'mainapp/contact.html')

def molinezia(request):
    return render(request, 'mainapp/molinezia.html')

def pecilia(request):
    return render(request, 'mainapp/pecilia.html')

def neon(request):
    return render(request, 'mainapp/neon.html')


# def product(request, pk = None):
#     product = product.name
#      if product.name == 'Молинезия черная':
#         return render(request, 'mainapp/molinezia.html')

lesson_1/geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}

    {% block css%}
    {% endblock %}


</head>
<body>
 <div class="container">
     {% include 'mainapp/includes/inc_menu.html' %}
     {% block content %}
     {% endblock %}

     {% block js %}
     {% endblock %}

     <div class="footer">
         <h5>Все права защищены &copy; 2019</h5>
     </div>
 </div>
</body>
</html>

lesson_1/geekshop/mainapp/templates/mainapp/catalog1.html
{% extends 'mainapp/base.html' %}


{% block title %}
    <title>Каталог</title>
{% endblock %}

{% block content %}
    <div class="catalog">
    <h2>Каталог</h2>
    <div class="molly">
         <img src="/static/img/molinez%20black.jpg" width="300" height="200" alt="Молинезия черная">
    </div>
   <div class="molly_ref">
      <a href="/molinezia/">Молинезия черная</a>
   </div>
    <div class="pecilia">
        <img src="/static/img/neon.jpg" width="300" height="200" alt="Неон голубой">
    </div>
    <div class="pecilia_ref">
         <a href="/neon/">Неон голубой</a>
    </div>
    <div class="pecilia">
        <img src="/static/img/red%20pecilia.jpg" width="300" height="200" alt="Пецилия красная">
    </div>
    <div class="pecilia_ref">
         <a href="/pecilia/">Пецилия красная</a>
    </div>

{% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}


        {% block title %}
        <title>Контакты</title>
        {% endblock %}

        {% block content %}
        <h3>Контакты</h3>
        <h4>Обратная связь:</h4>
        <form action=""> Ваше имя
            <br>
            <input type="text" , placeholder="Имя">
            <br> Ваш e-mail
            <br>
            <input type="text" , placeholder="Ваша почта">
            <br> Ваш вопрос
            <br>
            <input type="text" style="width: 600px; height: 80px" , placeholder="Задайте вопрос или оставьте пожелание">
            <br>
            <input type="submit"> </form>
        <br>
        <h4>Наш адрес: </h4>
        <p>МО, г. Краснознаменск, ул. Парковая д. 4</p>
        <div class="karta">
            <h4>Карта:</h4>
            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A1a630efc310ed0a7d7cac98b760fabba2f3983f7378397c6e0cabba0ded46e04&amp;width=100%25&amp;height=374&amp;lang=ru_RU&amp;scroll=true"></script>
        
        </div>
      {% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/hot_product.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Продукты</h1>
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }}</div>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
        <div style="margin: 20px" class="block">
              <div class="card" style="width: 18rem;">
                  <img src="/media/{{ hot_product.image }}" class="card-img-top" alt="hot_product">
                  <div class="card-body">
                      <h5 class="card-title">{{ hot_product.name }}</h5>
                      <h1 style="color: red;">ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ</h1>
                      <div style="color: red;">На складе осталось {{hot_product.quantity}} шт. Спешите!!!!!!!</div>
                      <a href="{% url 'basket:add' hot_product.pk %}">Добавить в корзину</a>
                      <br>
                      <a href="{% url 'basket:remove' hot_product.pk %}">Удалить из корзины</a>
                  </div>
              </div>
          </div>
    </div>
{% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block title %}
<title>Главная</title>
{% endblock %}


       {% block content %}
        <div class="welcom">
            <p>{% now "jS F Y" %}</p>
            <h1>Интернет-магазин АкваФиш</h1>
            {% if request.user.is_authenticated  %}
            <p>Мы рады приветствовать Вас, {{ request.user.username|title }}, на сайте нашего интернет-магазина. Мы откроем Вам красочный подводный мир!</p>
            <br>
            <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
             <a href="{% url "auth:logout" %}">Выйти</a>
        <br>
        <a href="{% url "auth:edit" request.user.pk %}">Редактировать профиль</a>
    {% else %}
         <p>Мы рады приветствовать Вас, на сайте нашего интернет-магазина. Мы откроем Вам красочный подводный мир!</p>
        <a href="{% url "auth:login" %}">Войти</a>
        <br>
        <a href="{% url "auth:register" %}">Зарегистрироваться</a>
    {% endif %}
        </div>

{% endblock %}
        

lesson_1/geekshop/mainapp/templates/mainapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello World</title>
</head>
<body>
<h1>Привет мир!</h1>
</body>
</html>

lesson_1/geekshop/mainapp/templates/mainapp/molinezia.html
{% extends 'mainapp/base.html' %}


        {% block title %}
    <title>Интернет-магазин AqvaFish</title>
{% endblock %}

{% block content %}

        <h1>Моллинезия черная</h1>
        <h3 class="product">Описание товара</h3>
        <br>
        <div class="foto_product">
            <a href="/static/img/molinez%20black.jpg" target="_blank"><img class="product" src="/static/img/molinez%20black.jpg"></a>
        </div>
        <div class="short_des" >
            <p class="all">Моллинезия (лат. Mollienesia): черная, снежинка, велифера, сфенопс, латипина — какую из этих видов ни назови, все они популярны и распространены в аквариуме и относятся к одному виду, хотя выглядят порой очень по-разному. А все из-за того, что у них много плюсов — они мирные, очень выносливые и неприхотливые, недорогие, и просто размножаются. Это чисто американские рыбы, так как живут они в Северной и Южной Америке. </p>

            <button class="shop">Купить</button>
        
        </div>
        <div class="description">
            <h3 class="product">Характеристики товара</h3>
        <table>
            <tr>
                <td>№ п/п</td>
                <td>Размер рыбы</td>
                <td>Наличие</td>
            </tr>
            <tr>
                <td>1</td>
                <td>3-4 см</td>
                <td>5 шт</td>
            </tr>
            <tr>
                <td>2</td>
                <td>5-6 см</td>
                <td>8 шт</td>
            </tr>
        </table>
        <h4>Требования и условия:</h4>
        <ul class="list">
            <li>Объём аквариума — от 50 л.</li>
            <li>Температура — 16–22 °C</li>
            <li>Значение pH — 7.0–8.0</li>
            <li>Жёсткость воды — от мягкой до очень жёсткой (5–25 dGH)</li>
            <li>Тип субстрата — любой</li>
            <li>Освещение — умеренное</li>
        </ul>
        <h3 class="product">Краткое описание</h3>
        <p class="little">Живородящая рыбка.
            <br> Размер 4-5 см
            <br> Простые и неприхотливые рыбки, которые хорошо подходят для содержания начинающими аквариумистами. Особенно это касается популярной и распространенной черной молли. Осторожно нужно быть только с дисковыми формами или как их еще называют — баллон, из-за своей искривленной формы продолжительность их жизни меньше чем у нормальных рыб. Дело в том, что форма баллона это сколиоз, со всеми вытекающими из него последствиями.</p>
        <h4>Питание</h4>
        <p class="little">Принимает большинство популярных кормов в сухом, замороженном и живом виде. Хорошим выбором станут корма, изготовленные специально для Моллинезий, выпускаемые многими производителями. Они уже содержат все необходимые вещества, в том числе растительные добавки — обязательный элемент в ежедневном рационе питания.</p>
        <h4>Разведение</h4>
        <p class="little">Хотя содержание сопряжено некоторыми сложностями, но если обеспечить благоприятную среду обитания, то нерест не заставит себя ждать. Половой зрелости самки достигают к 5–7 месяцам. Самцы созревают к 3–4 месяцам, но в ряде случаев процесс может растянуться до 6–7 месяцев. Инкубационный период длится около 30 дней. Мальки рождаются полностью сформировавшимися и готовыми принимать корм.</p>
        <br>
        <p class="little">Кормить специальными продуктами для выкармливания молоди (порошки, суспензии) и/или микроорганизмами, такими как науплии артемий. В качестве альтернативы допустимо использовать обычный корм в виде хлопьев, предварительно раскрошенный на маленькие фрагменты, чтобы мальки могли их проглотить. Взрослые Моллинезии склонны съедать своё собственное потомство, поэтому для его сохранности весь выводок следует пересаживать в отдельный резервуар.</p> <a href="/neon/">Неон голубой</a>
        </div>
       {% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/neon.html
{% extends 'mainapp/base.html' %}


        {% block title %}
    <title>Интернет-магазин AqvaFish</title>
{% endblock %}

{% block content %}

        <h1>Неон голубой</h1>
        <h3 class="product">Описание товара</h3>
        <br>
        <div class="foto_product">
            <a href="/static/img/neon.jpg" target="_blank"><img class="product" src="/static/img/neon.jpg" style=" width: 470px;"></a>
        </div>
        <div class="short_des" >
            <p class="all">Неон одна из самых популярных и известных рыбок. Яркая, блестящая, шустрая рыбка. Маленькая  - самцы до 3 см, самки до 3.5 см. в длину. Неоны стайные рыбки, лучше всего их содержать в просторном аквариуме от 50 литров большой группой от 10 штук. Чем больше неонов, тем красивее будет «переливаться» Ваш аквариум.</p>
            
            <button class="shop">Купить</button>
        
        </div>
        <div class="description">
            <h3 class="product">Характеристики товара</h3>
        <table>
            <tr>
                <td>№ п/п</td>
                <td>Размер рыбы</td>
                <td>Наличие</td>
            </tr>
            <tr>
                <td>1</td>
                <td>3-4 см</td>
                <td>5 шт</td>
            </tr>
            <tr>
                <td>2</td>
                <td>5-6 см</td>
                <td>8 шт</td>
            </tr>
        </table>
        <h4>Требования и условия:</h4>
        <ul class="list">
            <li>Объём аквариума — от 50 л.</li>
            <li>Температура — 16–22 °C</li>
            <li>Значение pH — 7.0–8.0</li>
            <li>Жёсткость воды — от мягкой до очень жёсткой (5–25 dGH)</li>
            <li>Тип субстрата — любой</li>
            <li>Освещение — умеренное</li>
        </ul>
        <h3 class="product">Краткое описание</h3>
        <p class="little">Икромечащуя рыбка.
            <br> Размер 4-5 см
            <br> Содержание голубого неона по силам даже начинающему аквариумисту. Однако нужно учитывать некоторые нюансы: Рыбка плохо переносит подмены воды в больших количествах (25% раз в неделю достаточно); Если рацион скудный, окраска голубого неона тускнеет; Важно строго следить за чистотой воды. Если заносите в аквариум новый предмет, его нужно сначала продезинфицировать. Дело в том, что голубые неоны подвержены грибковому заболеванию – плистифорозу, которое не лечится и приводит к летальному исходу.</p>
        <h4>Питание</h4>
        <p class="little">Принимает большинство популярных кормов в сухом, замороженном и живом виде. Хорошим выбором станут корма, изготовленные специально для Моллинезий, выпускаемые многими производителями. Они уже содержат все необходимые вещества, в том числе растительные добавки — обязательный элемент в ежедневном рационе питания.</p>
        <h4>Разведение</h4>
        <p class="little">Половой зрелости неон голубой достигает в возрасте 5-8 месяцев. Чем моложе рыбки, тем активнее они размножаются. Разведение включает в себя следующие этапы. Производителей отсаживают в раздельные аквариумы с такими параметрами: температура 18-20 градусов, 25% дистиллированной воды, понижение жёсткости до 4 dH, кислотность 5,5-6,5 рН. Рыбок кормят только живым кормом, исключая трубочника. Нерестовик для двух рыбок берут объёмом 10 литров. Дезинфицируют и устанавливают на дно сепараторную сетку. В нерестовике устанавливают следующие параметры воды: температура 23-25 градусов, жёсткость до 3 dH, кислотность 6-6,5 рН. Учтите, что процесс оплодотворения икры голубых неонов возможен только в мягкой воде. Перед нерестом желательно переместить аквариум в тёмное место или обклеить с трёх сторон бумагой тёмно-зелёного цвета. Самку и самца высаживают в нерестовик ночью. Обычно нерест начинается уже на утро и длится 3-4 часа. За это время самка успевает произвести до 150 икринок. После нереста производителей пересаживают обратно в общий аквариум, а нерестовик с икрой затемняют. Инкубационный период длится сутки. Сначала появляются личинки, а через 4-5 дней они становятся мальками. Стартовые корма: зоопланктон, коловратки, инфузории, вареный желток яйца.</p>
        <br>
        <p class="little">Кормить специальными продуктами для выкармливания молоди (порошки, суспензии) и/или микроорганизмами, такими как науплии артемий. В качестве альтернативы допустимо использовать обычный корм в виде хлопьев, предварительно раскрошенный на маленькие фрагменты, чтобы мальки могли их проглотить. Взрослые Моллинезии склонны съедать своё собственное потомство, поэтому для его сохранности весь выводок следует пересаживать в отдельный резервуар.</p> <a href="/pecilia/">Пецилия красная</a>
        </div>
       {% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/pecilia.html
{% extends 'mainapp/base.html' %}


        {% block title %}
    <title>Интернет-магазин AqvaFish</title>
{% endblock %}

{% block content %}
        <h1>Пецилия красная</h1>
        <h3 class="product">Описание товара</h3>
        <br>
        <div class="foto_product">
        <a href="/static/img/red%20pecilia.jpg" target="_blank"><img class="product" src="/static/img/red%20pecilia.jpg"></a>
        </div>
        <div class="short_des" >
        
        <p class="all">Пецилия красная, англоязычное торговое название Red Platy Fish, в Америке в качестве синонима также используется Coral Platy. Является декоративной разновидностью обычной Пецилии (Xiphophorus maculatus).</p>
                        
                        <button class="shop">Купить</button>
        
        </div>
        <div class="description">
            <h3 class="product">Характеристики товара</h3>
            <table>
                <tr>
                    <td>№ п/п</td>
                    <td>Размер рыбы</td>
                    <td>Наличие</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>3-4 см</td>
                    <td>5 шт</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>5-6 см</td>
                    <td>8 шт</td>
                </tr>
            </table>
            <h4>Требования и условия:</h4>
            <ul class="list">
                <li>Объём аквариума — от 50 л.</li>
                <li>Температура — 16–22 °C</li>
                <li>Значение pH — 7.0–8.0</li>
                <li>Жёсткость воды — от мягкой до очень жёсткой (5–25 dGH)</li>
                <li>Тип субстрата — любой</li>
                <li>Освещение — умеренное</li>
            </ul>
            <h3 class="product">Краткое описание</h3>
            <p class="little">Живородящая рыбка.
                <br> Размер самцов до 3 см, самок - до 5 см.
                <br> Обитает в водоемах Южной Мексики и Гватемалы. Самец отличается от самки наличием гоноподия.</p>
            <h4>Питание</h4>
            <p class="little">Основой ежедневного рациона питания могут стать любые популярные корма в сухом, замороженном и живом виде. Кроме того, многие производители выпускают специальную линейку кормов для Пецилий.</p>
            <h4>Разведение</h4>
            <p class="little">Половой зрелости достигают к 3–4 месяцам. Самки рождают полностью сформировавшихся мальков в количестве 20–40 штук. Родительские инстинкты не развиты, поэтому молодь необходимо пересаживать в другой аквариум во избежание хищничества. В благоприятных условиях нерест происходит каждые 4–6 недель.</p> <a href="/molinezia/">Моллинезия черная</a>

            {% endblock %}

lesson_1/geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Каталог</title>
{% endblock %}

{% block content %}

    <h1>Продукты</h1>
    <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
    <div>Общая стоимость корзины: {{ request.user|basket_total_cost }} руб.</div>
    <ul>
        {% include 'mainapp/includes/inc_category_menu.html' %}
        <br>
        {% for product in products %}
        <div class="block">
            <img class="product" src={{ product.image.url }} style="width: 470px;">
            <br>
            <a href={% if product.name == 'Молинезия черная' %}
            /molinezia/
            {% elif product.name == 'Неон голубой' %}
            /neon/
            {% elif product.name == 'Пецилия красная' %}
            /pecilia/
            {% endif %}>{{product.name}}</a>
            <p>{{product.category.name}}</p>
            <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
            <br>
            <a href="{% url 'basket:remove' product.pk %}">Удалить из корзины</a>
        </div>
        {% endfor %}
    </ul>

{% endblock %}