lesson_1/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

lesson_1/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path ('', mainapp.main, name='main'),
    path ('contact/', mainapp.contact, name='contact'),
    path ('products/', include('mainapp.urls', namespace='products')),
    path ('molinezia/', mainapp.molinezia, name='molinezia'),
    path ('neon/', mainapp.neon, name='neon'),
    path ('pecilia/', mainapp.pecilia, name='pecilia'),
    path ('auth/', include('authapp.urls', namespace='auth')),
    path ('admin/', admin.site.urls),
    path ('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson_1/geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    # path('product/{{product.name}}/', product.name, name={{product.name}}),
]

lesson_1/geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    # short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

lesson_1/geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product



def main(request):
    return render(request, 'mainapp/index.html')

def products(request, pk=None):
    products = Product.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()

    if pk is not None:
        if pk:
           category = get_object_or_404(ProductCategory, pk=pk)
           products = products.filter(category=category)

        context = {'products': products, 'categories': ProductCategory.objects.all(), 'basket': basket, }
        return render(request, 'mainapp/products.html', context)

    else:
        hot_product = Product.objects.filter(is_hot=True).first()

        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all(), 'basket': basket, }
        return render(request, 'mainapp/hot_product.html', context)


def contact(request):
    return render(request, 'mainapp/contact.html')

def molinezia(request):
    return render(request, 'mainapp/molinezia.html')

def pecilia(request):
    return render(request, 'mainapp/pecilia.html')

def neon(request):
    return render(request, 'mainapp/neon.html')


# def product(request, pk = None):
#     product = product.name
#      if product.name == 'Молинезия черная':
#         return render(request, 'mainapp/molinezia.html')

lesson_1/geekshop/mainapp/templates/mainapp/includes/inc_category_menu.html
<a style="margin: 0 20px" href="{% url 'products:category' 0 %}"
   class="{% if request.resolver_match.kwargs.pk == 0 %}
            active-menu
          {% endif %}">
    Все
</a>
{% for category in categories %}
    <a style="margin: 0 20px" href="{% url 'products:category' category.pk %}"
       class="{% if request.resolver_match.kwargs.pk == category.pk %}
                active-menu
              {% endif %}">
        {{ category.name }}
    </a>
{% endfor %}

lesson_1/geekshop/mainapp/templates/mainapp/includes/inc_menu.html
        <div class="header">
            <div class="logo"></div>
            <div class="b_menu">
                <ul class="menu">
                    <li>МЕНЮ</li>
                    <li><a href="/">Главная</a></li>
                    <li><a href="/products/">Каталог</a></li>
                    <li><a href="/contact/">Контакты</a></li>
                    <li><a href="/basket/">Корзина</a></li>
                </ul>
            </div>
        </div>